spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/searcher
    username: postgres
    password: A1234567
    driver-class-name: org.postgresql.Driver
  liquibase.enabled: true

application:
  sites:
    -
      url: 'https://lenta.ru/'
      name: 'Lenta'
